import { Inter } from "next/font/google";
import "./globals.css";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter";
import Providers from "../lib/Providers";

const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  title: "ReUI",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" sizes="32x32" type="image/x-icon" href="/logo.png" />
      </head>
      <body className={inter.className}>
      <Providers>
        <AppRouterCacheProvider>
          {children}
        </AppRouterCacheProvider>
        </Providers>
      </body>
    </html>
  );
}
