import { Inter } from "next/font/google";
import "./globals.css";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter";
import Providers from "../lib/Providers";

const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" type="image/png" sizes="32x32" href="/logo_w.png" />
        <link rel="icon" type="image/x-icon" href="/favicon.ico" />
        <title>ReUI</title>
      </head>
      <body className={inter.className}>
      <Providers>
        <AppRouterCacheProvider>
          {children}
        </AppRouterCacheProvider>
        </Providers>
      </body>
    </html>
  );
}
